fix(480): remove dep from data protection test
- as expected, this proves that the test breaks with
- `java.lang.NoClassDefFoundError: io/axoniq/framework/messaging/eventhandling/deadletter/SequencedDeadLetterQueueFactory`